# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:55:51+00:00

from __future__ import annotations

from pydantic import BaseModel


class JsonGetResponse(BaseModel):
    pass
